### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by anqima-ai** [JinyuanSun/ChatMol#14]
This is the error message after typing the first line into the command line of PyMOL

PyMOL>run https://raw.githubusercontent.com/JinyuanSun/ChatMol/main/chatmol.py
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/2.5.0/libexec/lib/python3.9/site-packages/pymol/parsing.py", line 467, in run
    run_(path, ns_pymol, ns_pymol)
  File "/usr/local/Cellar/pymol/2.5.0/libexec/lib/python3.9/site-packages/pymol/parsing.py", line 516, in run_file
    execfile(file,global_ns,local_ns)
  File "/usr/local/Cellar/pymol/2.5.0/libexec/lib/python3.9/site-packages/pymol/parsing.py", line 511, in execfile
    exec(co, global_ns, local_ns)
  File "https://raw.githubusercontent.com/JinyuanSun/ChatMol/main/chatmol.py", line 2, in <module>
    PyMOL Molecular Graphics System
ModuleNotFoundError: No module named 'openai'

But I have installed openai using PIP

(anaconda3)xxx-MacBook-Air:~ xxx$ which openai
/Users/xxx/opt/anaconda3/bin/openai

(anaconda3)xxx-MacBook-Air:~ xxx$ which pymol
/usr/local/bin/pymol

(anaconda3)xxx-MacBook-Air:~ xxx$ which python
/Users/xxx/opt/anaconda3/bin/python

Is this because my open sources PyMOL was installed at a different folder? Thanks!

**Comment by jiaboli007** [comment]
Make sure you install openai in PyMOL command line, like this:

<img width="238" alt="image" src="https://github.com/JinyuanSun/ChatMol/assets/15619907/05deee0f-de92-480e-9353-b11a9d0755e6">

**Comment by songyongshun** [comment]
I use the Education Only version 2.5.4 on windows, also having the same error. 
I had run "pip install openai" in PyMOL command line, and the message said the installation is success.
